################################################################################
# Compare changes in particle size distributions over time between two
# two reactors, using data taken from image analysis as desribed in
# the paper "Measuring the shape and size of activated sludge particles 
# immobilized in  agar with an open source software pipeline" submitted to 
# [JOVE](https://www.jove.com/).
#
# Joseph E. Weaver
# jeweave4@ncsu.edu
# joe.e.weaver@gmail.com
# NC State University
#
################################################################################


# Include packages --------------------------------------------------------
library("here")      # portably manage directory locations relative to .Rproj
library("readr")     # For reading CSV files generated by SParMorIA
library("dplyr")     # For sensible management dataframes
library("tidyr")     # Bring in the entire tidyverse
library("purrr")     # Adds some functional programming
library("stringr")   # Text manipulation
library("lubridate") # datestring to date object conversion and manipulation
library("ggplot2")   # grammar of graphcs, greatly improves figure generation
library("Cairo")     # Antialiased graphics, particularly usefuon on windows

# Read in particle data from multiple csvs --------------------------------

# Use the here package to specify the location of the data directory
data_dir = here::here("data","two_reactor_time_series")

# Get a list of all CSV files in data dir
files <- dir(data_dir, pattern = "*.csv")

# Read each CSV file and combine all the particle data into one dataframe
# Inspired by the code listed at:
# http://serialmentor.com/blog/2016/6/13/reading-and-combining-many-tidy-data-files-in-R
data <- data_frame(filename = files) %>%
   mutate(file_contents = map(filename,
                              ~ read_csv(file.path(data_dir, .)))
   )
data <- unnest(data)


# Append metadata ---------------------------------------------------------

# There is probably experimental metadata we would like to incorporate. For
# example, things sampling date, the reactor from which the sample came, or
# even annotations like 'cloudy effluent'.
#
# There are two good ways to deal with this, including the metadata in
# the filename itself or by including it in a separate file.
#
# In the case of base metadata, like dates and reactor names, I prefer to
# store the information direclty in the filename.  These can be split out
# and added as new columns to our data frame.

# First, let's get the reactor number
data$reactor <-  stringr::str_match(data$filename, "reactor-(\\d+)_")[,2]

# Now, get the date and  convert it to a more useful format
data$sampleDate <- ymd_hm(stringr::str_match(
                          data$filename, "date-([\\d|-]+)_")[,2])

# In the case of external metadata, we can record observations in an external
# file, read it into a dataframe, then merge the result with our existing
# data.  For example, let's say that reactor 1 was 'yeasty' on 2017-12-19
# and reactor 2 was 'vinegary' on 2017-12-08.
#
# We could record that data in a csv (viewable in data/observations.csv)
# and then read and merge, like so:

# read and prepare metadata
# note, we're specifying 'reactor' should be read a string
# this matches the format of the reactor name in 'data'
smells <- read_csv(here::here("data", "observations.csv"),
                   col_types = cols(reactor = "c"))
smells$sampleDate <- ymd_hm(smells$date) # makes it easier to merge by date

# merge with existing data
data <- left_join(data,smells, by = c("sampleDate", "reactor"))

# Data processing ---------------------------------------------------------
#
# Often we will want to further process the data before plotting it.
# For example, we may want to plot particles by the log of their
# equivalent diameter, rather than as total area.

data$eqd_um <- sqrt(data$Area * 1e8 / 2) / pi
data$log_eqd_um <- log10(data$eqd_um)

# Let's also turn dates into experiment days

start_date <- ymd_hm("2017-12-08-1200")
data$Day <- round(as.duration(interval(
                  start_date, data$sampleDate)) / ddays(1))

# Figure generation ------------------

# While data importing, metadata attachment, and (to some extent) data
# processing will be similar between experiments, there is almost an infinite
# variety of figures which can be generated.  Here, we generate a simple
# violin plot to give an example of how the dataframe we've generated can
# be used in conjunction with the ggplot2 package.


# some defaults often used to improve base ggplot2
theme_classic()
theme_update(panel.background = element_blank(),
             legend.position = "none",
             axis.line.x = element_line(color = "black", size = 1),
             axis.line.y = element_line(color = "black", size = 1),
             axis.ticks.x = element_line(color = "black", size = 1),
             axis.ticks.y = element_line(color = "black", size = 1),
             text=element_text(size = 12),
             axis.text=element_text(size=12,color = "black"),
             strip.text=element_text(size = 12))



# Create a series of violin plots of the particles in each reactor
# and show how they change over time

smelly <- group_by(data, reactor, Day) %>%
   summarise(lab = unique(smell), max_val = max(log_eqd_um))

p <- ggplot(data, aes(reactor, log_eqd_um,group = reactor, fill = reactor)) +
  geom_violin() +
  facet_grid(. ~ Day, labeller = label_both) +
  geom_text(data = smelly, aes(y = max_val*1.15, label = lab), angle = 90) +
  xlab("Reactor") + ylab("log Diameter (μm)")

# View the plot on local device
# Note that on screen devices, line thicknesses and text sizes which are
# appropriate for output to vector and high dpi graphics may look comically
# large

# CairoWin()
# p

# Save as an SVG
CairoSVG(file = here::here("output", "two_reactor_time_series.svg"),
         width = 7, height = 3, onefile = TRUE, bg = "white",
         family = c("Calibri", "Helvitica", "sans"), pointsize = 12)
p
dev.off()

# Save as PDF
# wil have warnings about 'encoding' and 'pagecentre' options. These are
# ignored by CairoPDF.
CairoPDF(file = here::here("output", "two_reactor_time_series.pdf"),
         width = 7, height = 3, onefile = TRUE, bg = "white",
         family = c("Calibri", "Helvitica", "sans"), pointsize = 12)
p
dev.off()


# Save our session info ------------------

sink(here::here("output", "two_reactor_time_series.R.sessionInfo.txt"))
sessionInfo()
sink()
