################################################################################
# Compare changes in particle size distributions over time between two
# two reactors, using data taken from image analysis as desribed in
# the paper XXX title name XXX in JOVE XXX pub info XXX
#
# Joseph E. Weaver
# jeweave4@ncsu.edu
# joe.e.weaver@gmail.com
# NC State University
#
################################################################################

# Include packages --------------------------------------------------------
library("here")      # portably manage directory locations relative to .Rproj
library("readr")     # For reading CSV files generated by SParMorIA
library("dplyr")     # For sensible management dataframes
library("tidyr")     # Bring in the entire tidyverse
library("purrr")     # Adds some functional programming


# Read in particle data from multiple csvs --------------------------------

# Use the here package to specify the location of the data directory
data_dir = here::here("data")

# Get a list of all CSV files in data dir
files <- dir(data_dir, pattern = "*.csv")

# Read each CSV file and combine all the particle data into one dataframe
# Inspired by the code listed at:
# http://serialmentor.com/blog/2016/6/13/reading-and-combining-many-tidy-data-files-in-R
data <- data_frame(filename = files) %>%
   mutate(file_contents = map(filename,
                              ~ read_csv(file.path(data_dir, .)))
   )
data <- unnest(data)
